name: "Set up Go - Gobrew"
author: "kevincobain2000"
description: "gobrew, setup go for Github Actions"
branding:
  icon: 'heart'
  color: 'green'

inputs:
  version:
    description: "go version"
    required: false
    default: "latest"
  working-dir:
    description: "working dir"
    required: false
    default: "."    
runs:
  using: "composite"
  steps:
    - name: gobrew setup
      run: |
        echo "$HOME/.gobrew/current/bin" >> $GITHUB_PATH
        echo "$HOME/.gobrew/bin"  >> $GITHUB_PATH
        echo "$HOME/go/bin"  >> $GITHUB_PATH
        curl -sLk https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | sh
      shell: bash

    - name: gobrew use
      working-dir: ${{ inputs.working-dir }}
      run: gobrew use ${{ inputs.version }}
      shell: bash
